### ISSUE TITLE
Not able to list all the <li> corresponding to the parameter I passed?

### ISSUE THREAD

**Issue by jojosuelobo** [jojosuelobo/WebScraping#1]
I'm web scraping an HTML page, and I want to store in a list all the <li> that have the string "is". However, the code is only storing the first two, and I don't know exactly what I'm doing wrong

I'm using BeautifulSoup to do the scraping
```html
<ul class="fun-facts">
     <li>Owned my dream car in high school <a href="#footer"><sup>1</sup></a></li>
     <li>Middle name is Ronald</li>
     <li>Never had been on a plane until college</li>
     <li>Dunkin Donuts coffee is better than Starbucks</li>
     <li>A favorite book series of mine is <i>Ender's Game</i></li>
     <li>Current video game of choice is <i>Rocket League</i></li>
     <li>The band that I've seen the most times live is the <i>Zac Brown Band</i></li>
   </ul>
```

My code
```python
import re

fun_facts = webpage.find('ul', attrs={'class', 'fun-facts'})
fun_facts_with_is = fun_facts.find_all('li', string=re.compile("is"))
fun_facts_with_is
```
Result returned
```
[<li>Middle name is Ronald</li>,
  <li>Dunkin Donuts coffee is better than Starbucks</li>]
```
The result I'm looking for:
```python
['Middle name is Ronald',
  'Dunkin Donuts coffee is better than Starbucks',
  "A favorite book series of mine is Ender's Game",
  'Current video game of choice is Rocket League',
  "The band that I've seen the most times live is the Zac Brown Band"]
```

**Comment by Vigtu** [comment]
Try this one :) 


import re
``
fun_facts = webpage.find('ul', attrs={'class': 'fun-facts'})
fun_facts_li = fun_facts.find_all("li")

fun_facts_li_is = []

for li in fun_facts_li:
    words = li.get_text()

    if "is" in words:
        fun_facts_li_is .append(li)

fun_facts_li_is

**Comment by Vigtu** [comment]
Try this one :) 


import re

fun_facts = webpage.find('ul', attrs={'class': 'fun-facts'})
fun_facts_li = fun_facts.find_all("li")

fun_facts_li_is = []

for li in fun_facts_li:
    words = li.get_text()

    if "is" in words:
        fun_facts_li_is .append(li)

fun_facts_li_is``

**Comment by jojosuelobo** [comment]
It worked! Thank you

**Comment by jojosuelobo** [comment]
Resolved
